from __future__ import annotations


MATERIAL_ANALYSIS_JOB_TYPE = "material_analysis"
PSKILL_BUILD_JOB_TYPE = "pskill_build"
PSKILL_COMPILE_JOB_TYPE = "pskill_compile"
PSKILL_TEST_JOB_TYPE = "pskill_test"
RUNTIME_STEP_JOB_TYPE = "runtime_step"
RUN_EVALUATION_JOB_TYPE = "run_evaluation"
GOVERNANCE_PROPOSAL_JOB_TYPE = "governance_proposal"
MEMORY_COMPACTION_JOB_TYPE = "memory_compaction"
SKILL_SYNC_JOB_TYPE = "skill_sync"

DEAD_LETTER_JOB_STATUS = "dead_letter"

LEGACY_COMPILE_JOB_TYPE = "compile"
LEGACY_RUNTIME_JOB_TYPE = "runtime"
LEGACY_SKILL_TEST_TIMELINE_DRIVER_JOB_TYPE = "skill_test_timeline_driver"

PSKILL_COMPILE_JOB_TYPES = (PSKILL_COMPILE_JOB_TYPE, LEGACY_COMPILE_JOB_TYPE)
PSKILL_TEST_JOB_TYPES = (PSKILL_TEST_JOB_TYPE, LEGACY_SKILL_TEST_TIMELINE_DRIVER_JOB_TYPE)
RUNTIME_STEP_JOB_TYPES = (RUNTIME_STEP_JOB_TYPE, LEGACY_RUNTIME_JOB_TYPE)

JOB_TYPE_FILTER_ALIASES = {
    PSKILL_COMPILE_JOB_TYPE: PSKILL_COMPILE_JOB_TYPES,
    LEGACY_COMPILE_JOB_TYPE: PSKILL_COMPILE_JOB_TYPES,
    PSKILL_TEST_JOB_TYPE: PSKILL_TEST_JOB_TYPES,
    LEGACY_SKILL_TEST_TIMELINE_DRIVER_JOB_TYPE: PSKILL_TEST_JOB_TYPES,
    RUNTIME_STEP_JOB_TYPE: RUNTIME_STEP_JOB_TYPES,
    LEGACY_RUNTIME_JOB_TYPE: RUNTIME_STEP_JOB_TYPES,
}

WORKER_CLAIM_JOB_TYPES = (
    PSKILL_COMPILE_JOB_TYPE,
    LEGACY_COMPILE_JOB_TYPE,
    RUNTIME_STEP_JOB_TYPE,
    LEGACY_RUNTIME_JOB_TYPE,
    PSKILL_TEST_JOB_TYPE,
    LEGACY_SKILL_TEST_TIMELINE_DRIVER_JOB_TYPE,
    MATERIAL_ANALYSIS_JOB_TYPE,
    PSKILL_BUILD_JOB_TYPE,
    RUN_EVALUATION_JOB_TYPE,
    GOVERNANCE_PROPOSAL_JOB_TYPE,
    MEMORY_COMPACTION_JOB_TYPE,
    SKILL_SYNC_JOB_TYPE,
)


def is_pskill_compile_job_type(value: str) -> bool:
    return value in PSKILL_COMPILE_JOB_TYPES


def is_pskill_test_job_type(value: str) -> bool:
    return value in PSKILL_TEST_JOB_TYPES


def is_runtime_step_job_type(value: str) -> bool:
    return value in RUNTIME_STEP_JOB_TYPES


def job_type_filter_values(value: str) -> tuple[str, ...]:
    return JOB_TYPE_FILTER_ALIASES.get(value, (value,))
